name: ussd_app
description: A new Flutter mobile app that uses ussd to operate
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  ussd_advanced: ^1.0.0
  go_router: ^7.0.2
  flutter_screenutil: ^5.8.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  flutter_hooks: ^0.18.6
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.1
  lottie: ^2.4.0
  animations: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


#  flutter_launcher_icons: ^0.13.1
#
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
#  image: assets/images/logo.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env


  fonts:
    - family: Sora-Regular
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf

    - family: Sora-Medium
      fonts:
        - asset: assets/fonts/Sora-Medium.ttf

    - family: Sora-Bold
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
